### ISSUE TITLE
Documentation code block issue

### ISSUE THREAD

**Issue by davidbrochart** [asphalt-framework/asphalt-mailer#23]
The YAML block doesn't display correctly on the [documentation website](https://asphalt.readthedocs.io/projects/mailer/en/latest/configuration.html):

![image](https://github.com/asphalt-framework/asphalt-mailer/assets/4711805/5fa4dddc-929d-4907-aba4-4b3fb5c46413)

It's fine if I build the documentation locally:

![image](https://github.com/asphalt-framework/asphalt-mailer/assets/4711805/8f8be927-ef10-4506-ab88-34e498e1bf18)

**Comment by agronholm** [comment]
Yeah, this is all because of `sphinx-rtd-theme`. I'm ditching this outdated and broken theme in my projects as I go.

**Comment by agronholm** [comment]
Closing this as `sphinx-rtd-theme` has been updated/fixed.
